### ISSUE TITLE
Add a disclaimer that this will CAUSE more re-renders, if you are already using reselect

### ISSUE THREAD

**Issue by m-andrew-albright** [theKashey/why-did-you-update-redux#1]
The use of this package cost my team hours of debugging to determine why our reselect selectors were being needlessly re-run when they very obviously should not have been.

It turns out the `beautiful-react-redux` package that is `require()`ed by this package is meant as a replacement for reselect, and does not play well with it, causing referential inequality on the args passed to the reselect selectors when nothing should have changed, forcing components to update needlessly.

**Comment by theKashey** [comment]
Yeah. First of all - sorry. Look like my "default" settings are not "default" for everyone.

Let me explain:
 - `why-did-you-update-redux` is just "cool-name" for `beautiful-react-redux`(not a cool name)
 - beautiful-react-redux uses HOF `shouldBePure` from `memoize-state`
 - `shouldBePure` checks the _purity_ of the function, and if it is not - ie returned _different_ result for the _same_ arguments - it throw. That's what this package does - checks the purity.

That is the problem - `shouldBePure` checks not only input and output but "something in between" - literally `pure` function should __access__ the same data to produce the same output. That's why it wipes everything, including cached reselect data on each run. This uber check is optional, but enabled by default.

Let me just disable it, and then lib should work fine with reselect.

**Comment by theKashey** [comment]
Should be fixed in 1.0.3

**Comment by theKashey** [comment]
Hey! Does it solves your issue?

**Comment by theKashey** [comment]
I've added more tests to the underlaying libraries, and could confirm that this issue got solved.

**Comment by m-andrew-albright** [comment]
Yes, I apologize I didn't respond sooner; thank you!
